[mongodb]
mongodb-dev.aravind381.online

[catalogue]
catalogue-dev.aravind381.online

[redis]
redis-dev.aravind381.online

[user]
user-dev.aravind381.online

[cart]
cart-dev.aravind381.online

[mysql]
mysql-dev.aravind381.online

[shipping]
shipping-dev.aravind381.online

[rabbitmq]
rabbitmq-dev.aravind381.online

[paymrnt]
payment-dev.aravind381.online

[frontend]
frontend-dev.aravind381.online

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.aravind381.online
CATALOGUE_HOST=catalogue-dev.aravind381.online
REDIS_HOST=redis-dev.aravind381.online
USER_HOST=user-dev.aravind381.online
CART_HOST=cart-dev.aravind.381.online
MYSQL_HOST=mysql-dev.aravaind.381.online
SHIPPING_HOST=shipping-dev.aravind381.online
RABBITMQ_HOST=rabbitmq-dev.aravind381.online
PAYMENT_HOST=payment-dev.aravind381.online
